### ISSUE TITLE
Details about the voxceleba-mini dataset in your paper.

### ISSUE THREAD

**Issue by imlixinyang** [wyhsirius/InMoDeGAN-project#1]
Generated results in you paper are very impressive. Can you share how you prepare the dataset so I can follow your work?

**Comment by wyhsirius** [comment]
@imlixinyang Thanks for your interest of our work. To prepare the dataset, we just randomly choose 2 video sequences of each identity from VoxCeleb2. We will release the chosen ids soon. Videos are downloaded from original voxceleb2 [website](https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox2.html).

**Comment by imlixinyang** [comment]
@wyhsirius Thank you for such a quick reply! I found that the file size is extremely large for the full VoxCeleb2 dataset, so I wonder that if there is a script to download only the videos used in you experiments.

**Comment by wyhsirius** [comment]
@imlixinyang Yes, the original dataset is extremely huge. Now we do not upload those videos online, but we plan to do it sooner.

**Comment by imlixinyang** [comment]
@wyhsirius OK! Thank you very much. I believe that video generation will become a hot topic recently and I'm looking forward to your update.

**Comment by wyhsirius** [comment]
@imlixinyang Thank you for the interest !

**Comment by KelestZ** [comment]
> @imlixinyang Thanks for your interest of our work. To prepare the dataset, we just randomly choose 2 video sequences of each identity from VoxCeleb2. We will release the chosen ids soon. Videos are downloaded from original voxceleb2 [website](https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox2.html).

In the paper (Sec.4.1 Paragraph{VoxCeleb2-mini}), it's said _20_ videos per subject. Is it a typo that should be _2_ in practice?

**Comment by KelestZ** [comment]
Another question I have about the dataset is that I noticed the face detection bounding boxes are often oscillating (e.g., /id02445/GKyI2XEiEeA/00020.mp4 in the TEST dataset and many others), did you have any data pre-processing steps to deal with the oscillation of the detection bounding boxes? 
Will appreciate your reply. Thanks.
